config/routes.rb
Mixlair::Application.routes.draw do
  devise_for :users

  get "home/index"
  get "mix/show"

  resources :mix

  root to: "mix#index"

end

app/models/chorus.rb
class Chorus < Effect
end

app/models/compressor.rb
class Compressor < Effect
end

app/models/delay.rb
class Delay < Effect
end

app/models/effect.rb
class Effect < ActiveRecord::Base
end

app/models/effects.rb
class Effect < ActiveRecord::Base
end

app/models/mix.rb
class Mix < ActiveRecord::Base
  belongs_to :user
  has_many :tracks, :dependent => :destroy

  accepts_nested_attributes_for :tracks

  validates :user_id, presence: true
end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :track
  # attr_accessible :title, :body
end

app/models/reverb.rb
class Reverb < Effect
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :mix
  has_many :regions, :dependent => :destroy
  has_many :effects, :dependent => :destroy

  accepts_nested_attributes_for :regions
  accepts_nested_attributes_for :effects

  # attr_accessible :title, :body
end

app/models/tremolo.rb
class Tremolo < Effect
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :mixes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mix_controller.rb
class MixController < ApplicationController
  before_filter :authenticate_user!
  respond_to :json, :html

  def create
    mix = Mix.new
    mix.user_id = current_user.id

    render json: mix
  end

  def show
    if @mix = current_user.mixes.find_by_id(params[:id])
      @mix
    else
      flash[:notice] = "no mix found with an id of #{params[:id]}"
      redirect_to mix_index_path
    end
  end

  def new
    mix = Mix.new
    mix.user_id = current_user.id

    if mix.save()
      redirect_to mix
    else
      flash[:notice] = "error creating new mix"
      redirect_to mix_index_path
    end
  end

  def index
    @mixes = current_user.mixes

    respond_with @mixes
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mixlair
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{name: 'description', content: 'Mixlair: Social audio editing'}
    = yield :head
  %body{class: controller.controller_name.to_s + " " + controller.action_name.to_s}
    #flash-messages
      - if !notice.nil?
        .notice= notice
      - if !alert.nil?
        .alert= alert
    = yield

  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', 'UA-41412618-1', 'mixlair.com');ga('send', 'pageview');

app/views/mix/index.html.haml
%h2 your tracks
=link_to("Create A Mix", new_mix_path)
- unless @mixes.empty?
  %ul
    - @mixes.each do |mix|
      %li= link_to(mix.name.blank? ? "untitled mix #{mix.id}" : mix.name, mix)
- else
  %h3 you have no mixes

app/views/mix/show.html.haml
- content_for :head do
  = javascript_include_tag "mix"
  = render partial: "./mix/templates/templates"
  %script
    window.MIX= #{raw(@mix.to_json)}
#header-mask
  %h1 mixlair.
  .label.left my tracks
%header
#mix
  #play-head
  .stage
    .loader
      .bar
    #chrome-warning
      mixlair is a chrome experiment. please open in
      %a{href: 'http://www.google.com/chrome'} google chrome
      to try it out!
  .effect-panel
    .list
  %footer#footer